#!/usr/bin/env python3
"""Generate the LaTeX drivers for the 35-question book and compile them.

Source of truth is topics/bodies/topic_NN.tex, hand-edited, plus the shared
topics/preamble.tex. This writes the thin drivers around them:

  topics/topic_NN.tex     standalone article, one question per PDF
  topics/book.tex         the collected book: one title page, one table of
                          contents, continuous pagination, the конспект's own
                          three parts, a \\chapter per question

and moves the result to the repository root as darzhaven-izpit-kn.pdf.

Chapters follow `topics/manifest.json`, which follows the official конспект —
not the filenames of the sources, which predate the June 2025 revision and
disagree with it (docs/CORPUS.md §3).

A question with no body yet gets a generated placeholder carrying its official
annotation: what the examiners require, what sources exist for it, and what is
known to be missing. That means the book compiles from the first day and reads
as a specification of the work remaining rather than failing to build at all —
and the two questions with no sources say so in the text instead of silently
being absent.

  python3 scripts/build_topics.py             # drivers + the book
  python3 scripts/build_topics.py --gen-only  # write drivers, do not compile
  python3 scripts/build_topics.py --all       # + a standalone PDF per question
"""
import argparse
import json
import os
import re
import shutil
import unicodedata
import subprocess
import sys

from check_structure import check as check_structure

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOPICS = os.path.join(ROOT, "topics")
BODIES = os.path.join(TOPICS, "bodies")
BOOK_PDF = os.path.join(ROOT, "darzhaven-izpit-kn.pdf")
BUILT_BOOK_PDF = os.path.join(TOPICS, "book.pdf")
MANIFEST = os.path.join(TOPICS, "manifest.json")
ANNOT = os.path.join(ROOT, "docs", "konspekt_annotations.json")

# The конспект's own division. Chapter numbers are question numbers.
PARTS = [
    (1, 8, "Основи на компютърните науки"),
    (9, 27, "Ядро на компютърните науки"),
    (28, 35, "Математика и приложения"),
]

AUTOGEN = ("%% AUTO-GENERATED by scripts/build_topics.py — do not edit.\n"
           "%% Edit topics/bodies/topic_%s.tex or topics/preamble.tex instead.\n")


def tex_escape(s):
    # The конспект sets variables in Mathematical Italic (U+1D400 block). No
    # text face carries those, so they come out as tofu boxes — the annotation
    # for question 11 rendered "i-тата двойка е ▨▨▨". NFKC folds them onto
    # their Latin base letters, which is what the surrounding prose is anyway.
    s = unicodedata.normalize("NFKC", s)
    for a, b in (("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"),
                 ("$", "\\$"), ("#", "\\#"), ("_", "\\_"),
                 ("{", "\\{"), ("}", "\\}"), ("~", "\\textasciitilde{}"),
                 ("^", "\\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def load():
    man = json.load(open(MANIFEST))["topics"]
    ann = json.load(open(ANNOT)) if os.path.exists(ANNOT) else {}
    return man, ann


def placeholder(n, meta, ann):
    """A body for a question not yet written, stating what it must contain."""
    src = []
    if meta.get("pdf"):
        src.append("PDF \\texttt{%s}" % tex_escape(meta["pdf"]))
    if meta.get("photos"):
        src.append("снимки \\texttt{%s}" % tex_escape(meta["photos"]))
    for e in meta.get("extra", []):
        src.append("\\texttt{%s}" % tex_escape(e))
    sources = ", ".join(src) if src else "\\textbf{няма източник}"

    body = [AUTOGEN % n,
            "%% Placeholder. Replace with the written chapter.\n"]
    if meta.get("confidence") == "gap":
        body.append(
            "\\begin{supp}[Липсващ източник]\n"
            "За този въпрос липсва какъвто и да е източник в наличния материал. "
            "Съдържанието по-долу е само формулировката от конспекта — "
            "главата предстои да бъде написана по друг източник.\n"
            "\\end{supp}\n\n")
    body.append("\\textit{Източници:} %s\n\n" % sources)
    if meta.get("note"):
        body.append("\\begin{supp}[Бележка към картографирането]\n%s\n"
                    "\\end{supp}\n\n" % tex_escape(meta["note"]))
    a = ann.get(str(n), "")
    if a:
        # The annotation is the specification: what the examiners ask for.
        body.append("\\subsection*{Анотация от конспекта}\n")
        body.append(tex_escape(a) + "\n")
    return "".join(body)


def ensure_bodies(man, ann):
    os.makedirs(BODIES, exist_ok=True)
    made = 0
    for n, meta in man.items():
        p = os.path.join(BODIES, "topic_%02d.tex" % int(n))
        if os.path.exists(p):
            continue
        open(p, "w").write(placeholder(int(n), meta, ann))
        made += 1
    return made


def standalone(n, title):
    return AUTOGEN % ("%02d" % n) + r"""\documentclass[11pt]{article}
\usepackage[a4paper, margin=1in]{geometry}
\input{preamble}
%% Match the collected book: the chapter number is the question number, while
%% statement and equation counters run continuously within it.
\renewcommand{\thesection}{%(n)d.\arabic{section}}
\renewcommand{\thethm}{%(n)d.\arabic{thm}}
\renewcommand{\theequation}{%(n)d.\arabic{equation}}
\hypersetup{pdftitle={Въпрос %(n)d. %(plain)s}}
\pagestyle{fancy}\fancyhf{}
\fancyhead[L]{\small\itshape Въпрос %(n)d}
\fancyhead[R]{\small\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\begin{document}
\renewcommand{\proofname}{Доказателство}
\begin{center}
  {\Large\bfseries Въпрос %(n)d.\ }{\Large %(title)s}
\end{center}
\vspace{1.2em}
\input{bodies/topic_%(nn)02d}
\end{document}
""" % {"n": n, "nn": n, "title": title, "plain": title}


def book(man):
    chapters = []
    for lo, hi, part in PARTS:
        chapters.append("\\part{%s}" % part)
        for n in range(lo, hi + 1):
            meta = man.get(str(n))
            if not meta:
                continue
            chapters.append("\\chapter{%s}\n\\input{bodies/topic_%02d}"
                            % (meta["title"], n))
    return ("% AUTO-GENERATED by scripts/build_topics.py — do not edit.\n"
            "% Edit topics/bodies/*.tex or topics/preamble.tex instead.\n"
            + r"""\documentclass[11pt,openany]{report}
\usepackage[a4paper, margin=1in, top=1.1in, bottom=1.1in]{geometry}
\input{preamble}
\numberwithin{thm}{chapter}
\hypersetup{pdftitle={Държавен изпит по Компютърни науки — записки}}
\pagestyle{fancy}\fancyhf{}
\fancyhead[L]{\small\itshape\leftmark}
\fancyhead[R]{\small\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\begin{document}
\renewcommand{\chaptername}{Въпрос}
\renewcommand{\partname}{Част}
\renewcommand{\proofname}{Доказателство}
\begin{titlepage}
\centering\vspace*{3cm}
{\Huge\bfseries Държавен изпит\par}\vspace{0.6cm}
{\LARGE Компютърни науки\par}\vspace{2cm}
{\large Записки по конспекта от 30.06.2025\par}
\vspace{0.4cm}
{\small ФМИ, Софийски университет „Св. Климент Охридски“\par}
\vfill
\end{titlepage}
\chapter*{Как да използвате записките}
Дефинициите въвеждат понятия и означения. Те не се доказват.
Теоремите, лемите, твърденията и следствията формулират проверими
резултати; след тях има отделен блок с доказателство.
Аксиомите и схемите изрично посочват приетите изходни предпоставки.

\begin{itemize}
\item Синя рамка: дефиниция.
\item Зелена рамка: теорема, лема, твърдение или следствие.
\item Златна рамка със звезда: основна дефиниция, резултат или аксиома.
\item Сива затворена рамка: доказателство, завършващо със символ $\square$.
\end{itemize}

Формулировките и номерацията следват конспекта от 30.06.2025.
В тази редакция са отделени определенията от обяснителния текст и са
допълнени доказателства към резултати, оставени без доказателство
в предходната редакция. Допълнените аргументи са учебна разработка,
а не дословен текст от конспекта. Използваните външни резултати са
посочени в съответното доказателство.

Бележките за липсващи първични източници по въпроси 11 и 12 остават
в началото на тези глави. Проверката на рамките и наличието на
доказателства не замества академичната проверка по литературата.
\clearpage
\tableofcontents
\cleardoublepage
""" + "\n\n".join(chapters) + "\n\\end{document}\n")


def compile_tex(name):
    r = subprocess.run(["tectonic", "-X", "compile", name],
                       cwd=TOPICS, capture_output=True, text=True)
    if r.returncode != 0:
        tail = (r.stderr or "")[-2500:]
        print("BUILD FAILED for %s:\n%s" % (name, tail))
        return False
    return True


def publish_book_pdf():
    """Atomically publish Tectonic's book PDF at the repository root."""
    if not os.path.isfile(BUILT_BOOK_PDF):
        raise FileNotFoundError("Tectonic did not produce %s" % BUILT_BOOK_PDF)
    os.replace(BUILT_BOOK_PDF, BOOK_PDF)
    return BOOK_PDF


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gen-only", action="store_true")
    ap.add_argument("--all", action="store_true",
                    help="also build one standalone PDF per question")
    args = ap.parse_args()

    man, ann = load()
    made = ensure_bodies(man, ann)
    if made:
        print("wrote %d placeholder bodies" % made)

    _, structure_errors = check_structure()
    if structure_errors:
        sys.exit("statement/proof structure failed:\n" + "\n".join(structure_errors))

    for n, meta in man.items():
        open(os.path.join(TOPICS, "topic_%02d.tex" % int(n)), "w").write(
            standalone(int(n), meta["title"]))
    open(os.path.join(TOPICS, "book.tex"), "w").write(book(man))
    print("wrote %d drivers + book.tex" % len(man))
    if args.gen_only:
        return

    if not shutil.which("tectonic"):
        sys.exit("tectonic not found — brew install tectonic")

    if compile_tex("book.tex"):
        published = publish_book_pdf()
        print("built %s" % os.path.relpath(published, ROOT))
    else:
        sys.exit(1)
    if args.all:
        for n in sorted(int(x) for x in man):
            if compile_tex("topic_%02d.tex" % n):
                print("  built topic_%02d.pdf" % n)


if __name__ == "__main__":
    main()
